spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.146.207.218:3306/big_data?setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useAffectedRows=true&useOldAliasMetadataBehavior=true
    username: root
    password: 883225